import os
import json
import sys
from openai import OpenAI
from github import Github

def extract_prompt():
    """پرامپت را از رویداد اجرا (Issue یا دستی) استخراج می‌کند."""
    event_name = os.environ.get('EVENT_NAME')
    event_payload = json.loads(os.environ.get('EVENT_PAYLOAD', '{}'))

    if event_name == 'issues':
        title = event_payload.get('issue', {}).get('title', 'No Title')
        body = event_payload.get('issue', {}).get('body', '')
        issue_number = event_payload.get('issue', {}).get('number')
        full_prompt = f"Project Title: {title}\n\nDescription:\n{body}"
        return full_prompt, issue_number

    elif event_name == 'workflow_dispatch':
        prompt = event_payload.get('inputs', {}).get('prompt', '')
        return prompt, None

    return None, None


def generate_code(prompt):
    """از Together AI برای تولید کد استفاده می‌کند."""
    client = OpenAI(
        api_key=os.environ['TOGETHER_API_KEY'],
        base_url="https://api.together.xyz/v1"
    )

    # پرامپت سخت‌گیرانه برای دریافت خروجی با فرمت درست
    strict_prompt = (
        "You are a code generator. Your output MUST be ONLY in the following format.\n"
        "DO NOT ADD ANY OTHER TEXT, EXPLANATIONS, OR NOTES OUTSIDE THE SPECIFIED BLOCKS.\n\n"
        "For each file, use EXACTLY this structure:\n\n"
        "# FILENAME: filename.py\n"
        "```\n"
        "code here\n"
        "```\n\n"
        "# FILENAME: README.md\n"
        "```\n"
        "# Project Title\n"
        "...\n"
        "```\n\n"
        "Generate the complete project for the following request:\n"
        + prompt
    )

    # استفاده از مدل رایگان و قدرتمند Qwen 2.5 Coder 32B
    response = client.chat.completions.create(
        model="Qwen/Qwen2.5-Coder-32B-Instruct",
        messages=[
            {"role": "system", "content": "You are a professional coding machine. You ONLY output in the strict format with # FILENAME: tags and code blocks."},
            {"role": "user", "content": strict_prompt}
        ],
        temperature=0.2,
        max_tokens=8000
    )
    
    return response.choices[0].message.content


def parse_response_to_files(text):
    """تجزیه پاسخ با فرمت # FILENAME: یا بازیابی اضطراری."""
    files = {}
    current_filename = None
    current_content = []
    lines = text.split('\n')
    
    for line in lines:
        if line.startswith('# FILENAME:'):
            if current_filename:
                files[current_filename] = '\n'.join(current_content).strip()
            current_filename = line.replace('# FILENAME:', '').strip()
            current_content = []
        elif current_filename:
            current_content.append(line)
    
    if current_filename:
        files[current_filename] = '\n'.join(current_content).strip()

    # اگر هیچ فایلی با این روش پیدا نشد، کل پاسخ را به عنوان فایل output.md ذخیره کن
    if not files:
        print("⚠️ مدل فرمت درخواستی را رعایت نکرد. کل پاسخ در فایل output.md ذخیره می‌شود.")
        clean_text = text.replace('```', '')
        files = {"output.md": f"# Raw AI Output\n\n{clean_text}"}
    
    return files


def create_github_repo(repo_name):
    """مخزن جدید را می‌سازد. در صورت شکست، Action را متوقف می‌کند."""
    try:
        g = Github(os.environ['GH_PAT'])
        user = g.get_user()
        repo = user.create_repo(
            name=repo_name,
            description="🤖 Generated by AI Code Generator",
            auto_init=True
        )
        print(f"✅ مخزن جدید ساخته شد: {repo.html_url}")
        return repo
    except Exception as e:
        print(f"❌ خطای مهلک در ساخت مخزن: {e}")
        sys.exit(1)


def push_files_to_repo(repo, files):
    """فایل‌ها را در مخزن آپلود می‌کند."""
    for filename, content in files.items():
        try:
            try:
                existing = repo.get_contents(filename)
                repo.update_file(
                    path=filename,
                    message=f"AI Update: {filename}",
                    content=content,
                    sha=existing.sha
                )
                print(f"🔄 بروزرسانی: {filename}")
            except:
                repo.create_file(
                    path=filename,
                    message=f"AI Commit: {filename}",
                    content=content
                )
                print(f"➕ ایجاد: {filename}")
        except Exception as e:
            print(f"❌ خطا در آپلود {filename}: {e}")
            print(f"⚠️ ادامه فرآیند با وجود خطا...")


def comment_on_issue(repo_name, issue_number, new_repo_url):
    """روی Issue کامنت می‌گذارد. در صورت شکست، فقط هشدار می‌دهد (مخزن ساخته شده)."""
    try:
        g = Github(os.environ['GH_PAT'])
        repo = g.get_repo(f"{os.environ['REPO_OWNER']}/{repo_name}")
        issue = repo.get_issue(number=issue_number)
        comment = (
            "🎉 **پروژه شما آماده است!**\n\n"
            "کدهای خواسته‌شده در یک مخزن جدید قرار گرفتند:\n\n"
            f"👉 **{new_repo_url}**\n\n"
            "کافیه روی لینک بالا کلیک کنی و پروژه‌ات رو ببینی.\n\n"
            "---\n"
            f"🤖 *این پروژه توسط [AI Code Generator](https://github.com/{os.environ['REPO_OWNER']}/{repo_name}) ساخته شده است.*"
        )
        issue.create_comment(comment)
        print(f"💬 کامنت روی Issue #{issue_number} ثبت شد.")
    except Exception as e:
        print(f"⚠️ خطا در ثبت کامنت (اما مخزن ساخته شده): {e}")


def main():
    print("🔄 دریافت درخواست کاربر...")
    prompt, issue_number = extract_prompt()
    
    if not prompt:
        print("❌ هیچ درخواستی یافت نشد.")
        sys.exit(1)
    
    print(f"📝 درخواست: {prompt[:200]}...")
    
    print("\n🤖 برقراری ارتباط با Together AI...")
    try:
        generated = generate_code(prompt)
    except Exception as e:
        print(f"❌ خطا در هوش مصنوعی: {e}")
        sys.exit(1)
    
    print("📦 تجزیه پاسخ...")
    files = parse_response_to_files(generated)
    print(f"📂 {len(files)} فایل آماده شد:")
    for f in files:
        print(f"   - {f}")
    
    repo_name = f"ai-project-{os.environ.get('GITHUB_RUN_ID', 'unknown')}"
    print(f"\n🏗️ ساخت مخزن: {repo_name}")
    new_repo = create_github_repo(repo_name)
    
    print("🚀 آپلود فایل‌ها...")
    push_files_to_repo(new_repo, files)
    
    if issue_number:
        current_repo = os.environ.get('GITHUB_REPOSITORY', '').split('/')[-1]
        comment_on_issue(current_repo, issue_number, new_repo.html_url)
    
    print("\n✅ عملیات با موفقیت پایان یافت.")


if __name__ == "__main__":
    main()
