import os
import json
import google.generativeai as genai
from github import Github

# --- توابع کمکی ---

def extract_prompt():
    """
    پرامپت رو از رویدادی که باعث اجرا شده درمیاره.
    اگه کاربر Issue باز کرده باشه، عنوان + توضیحات رو برمی‌گردونه.
    اگه دستی اجرا کرده باشه، متن ورودی رو برمی‌گردونه.
    """
    event_name = os.environ.get('EVENT_NAME')
    event_payload = json.loads(os.environ.get('EVENT_PAYLOAD', '{}'))

    if event_name == 'issues':
        title = event_payload.get('issue', {}).get('title', 'No Title')
        body = event_payload.get('issue', {}).get('body', '')
        issue_number = event_payload.get('issue', {}).get('number')
        # پرامپت نهایی
        full_prompt = f"Project Title: {title}\n\nDescription:\n{body}"
        return full_prompt, issue_number

    elif event_name == 'workflow_dispatch':
        prompt = event_payload.get('inputs', {}).get('prompt', '')
        return prompt, None

    return None, None


def generate_code(prompt):
    """از مدل Gemini گوگل میخوایم کد پروژه رو تولید کنه."""
    genai.configure(api_key=os.environ['GOOGLE_API_KEY'])
    
    # مدل سریع و خوب
    model = genai.GenerativeModel(
        model_name='gemini-1.5-flash',
        system_instruction=(
            "You are a professional AI coding assistant. Generate complete, runnable code for the given request. "
            "Respond ONLY with the following structured format:\n"
            "# FILENAME: <filename>\n```<code>```\n"
            "Repeat for each file needed. End with a README.md file."
        ),
        generation_config=genai.GenerationConfig(
            temperature=0.3,
            max_output_tokens=8000
        )
    )
    
    response = model.generate_content(prompt)
    return response.text


def parse_response_to_files(text):
    """خروجی مدل رو میگیریم و به دیکشنری فایل‌ها تبدیل می‌کنیم."""
    files = {}
    current_filename = None
    current_content = []
    
    for line in text.split('\n'):
        if line.startswith('# FILENAME:'):
            if current_filename:
                files[current_filename] = '\n'.join(current_content).strip()
            current_filename = line.replace('# FILENAME:', '').strip()
            current_content = []
        elif current_filename:
            current_content.append(line)
    
    # آخرین فایل هم ذخیره بشه
    if current_filename:
        files[current_filename] = '\n'.join(current_content).strip()
    
    return files


def create_github_repo(repo_name):
    """
    یک مخزن جدید روی اکانت ما میسازه و برمی‌گردونه.
    از توکن گیتهاب (GH_PAT) برای احراز هویت استفاده میکنه.
    """
    g = Github(os.environ['GH_PAT'])
    user = g.get_user()
    
    repo = user.create_repo(
        name=repo_name,
        description="🤖 Generated by AI Code Generator",
        auto_init=True   # یه README اولیه میذاره که بتونیم روش push کنیم
    )
    print(f"✅ مخزن جدید ساخته شد: {repo.html_url}")
    return repo


def push_files_to_repo(repo, files):
    """فایل‌های تولیدشده رو توی مخزن جدید آپلود میکنه."""
    for filename, content in files.items():
        try:
            # اگه فایل از قبل وجود داره، آپدیتش کن
            try:
                existing = repo.get_contents(filename)
                repo.update_file(
                    path=filename,
                    message=f"AI Update: {filename}",
                    content=content,
                    sha=existing.sha
                )
                print(f"🔄 بروزرسانی: {filename}")
            except:
                # اگه نیست، ایجادش کن
                repo.create_file(
                    path=filename,
                    message=f"AI Commit: {filename}",
                    content=content
                )
                print(f"➕ ایجاد: {filename}")
        except Exception as e:
            print(f"❌ خطا در آپلود {filename}: {e}")


def comment_on_issue(repo_name, issue_number, new_repo_url):
    """روی Issue اصلی یه کامنت میذاره و آدرس پروژه جدید رو میده."""
    g = Github(os.environ['GH_PAT'])
    repo = g.get_repo(f"{os.environ['REPO_OWNER']}/{repo_name}")
    issue = repo.get_issue(number=issue_number)
    
    comment = f"""
🎉 **پروژه شما آماده است!**

کدهای خواسته‌شده در یک مخزن جدید قرار گرفتند:

👉 **{new_repo_url}**

کافیه روی لینک بالا کلیک کنی و پروژه‌ات رو ببینی.

---
🤖 *این پروژه توسط [AI Code Generator](https://github.com/{os.environ['REPO_OWNER']}/{repo_name}) ساخته شده است.*
"""
    issue.create_comment(comment)
    print(f"💬 کامنت روی Issue #{issue_number} ثبت شد.")


# --- برنامه اصلی ---

def main():
    print("🔄 دریافت درخواست کاربر...")
    prompt, issue_number = extract_prompt()
    
    if not prompt:
        print("❌ هیچ درخواستی یافت نشد.")
        return
    
    print(f"📝 درخواست: {prompt[:200]}...")
    
    print("\n🤖 برقراری ارتباط با Google AI Studio...")
    try:
        generated = generate_code(prompt)
    except Exception as e:
        print(f"❌ خطا در هوش مصنوعی: {e}")
        return
    
    print("📦 تجزیه پاسخ...")
    files = parse_response_to_files(generated)
    
    if not files:
        print("⚠️ خروجی فاقد فایل بود.")
        return
    
    print(f"📂 {len(files)} فایل آماده شد.")
    for f in files:
        print(f"   - {f}")
    
    # یک اسم یکتا برای مخزن جدید
    repo_name = f"ai-project-{os.environ.get('GITHUB_RUN_ID', 'unknown')}"
    print(f"\n🏗️ ساخت مخزن: {repo_name}")
    new_repo = create_github_repo(repo_name)
    
    print("🚀 آپلود فایل‌ها...")
    push_files_to_repo(new_repo, files)
    
    # اگه از طریق Issue اجرا شده بود، کامنت بذار
    if issue_number:
        current_repo = os.environ.get('GITHUB_REPOSITORY', '').split('/')[-1]
        comment_on_issue(current_repo, issue_number, new_repo.html_url)
    
    print("\n✅ عملیات با موفقیت پایان یافت.")


if __name__ == "__main__":
    main()
