import os
import json
import sys
from google import genai
from github import Github

# لیست مدل‌هایی که پشت سر هم تست می‌شوند
MODEL_LIST = [
    "gemini-2.5-flash",
    "gemini-2.0-flash",
    "gemini-1.5-flash",
    "gemini-flash-latest",
    "gemini-pro",
    "models/gemini-1.5-flash",
    "models/gemini-2.5-flash",
]

def extract_prompt():
    event_name = os.environ.get('EVENT_NAME')
    event_payload = json.loads(os.environ.get('EVENT_PAYLOAD', '{}'))

    if event_name == 'issues':
        title = event_payload.get('issue', {}).get('title', 'No Title')
        body = event_payload.get('issue', {}).get('body', '')
        issue_number = event_payload.get('issue', {}).get('number')
        return f"Project Title: {title}\n\nDescription:\n{body}", issue_number
    
    elif event_name == 'workflow_dispatch':
        prompt = event_payload.get('inputs', {}).get('prompt', '')
        return prompt, None

    return None, None


def generate_code(prompt):
    """مدل‌های مختلف را امتحان می‌کند تا یک پاسخ معتبر بگیرد."""
    client = genai.Client(api_key=os.environ['GOOGLE_API_KEY'])
    
    strict_prompt = (
        "You are a strict code generator. You ONLY output code in the following format. "
        "NO extra text, NO explanations, NO notes outside the code blocks.\n\n"
        "For each file, use EXACTLY this structure:\n\n"
        "# FILENAME: filename.py\n"
        "```\n"
        "code here\n"
        "```\n\n"
        "# FILENAME: README.md\n"
        "```\n"
        "# Project Title\n"
        "...\n"
        "```\n\n"
        "Generate the complete project for the following request:\n"
        + prompt
    )

    last_error = None
    for model in MODEL_LIST:
        try:
            print(f"🔍 تلاش با مدل: {model}")
            response = client.models.generate_content(
                model=model,
                contents=strict_prompt,
                config={
                    'system_instruction': "You are a coding machine. You ONLY output in the strict format with # FILENAME: tags and code blocks.",
                    'temperature': 0.3,
                    'max_output_tokens': 8000
                }
            )
            print(f"✅ مدل {model} با موفقیت پاسخ داد.")
            return response.text
        except Exception as e:
            last_error = e
            print(f"⚠️ مدل {model} شکست خورد: {e}")
            continue
    
    # اگر هیچ مدلی جواب نداد
    raise RuntimeError(f"هیچ‌یک از مدل‌های لیست کار نکرد. آخرین خطا: {last_error}")


def parse_response_to_files(text):
    files = {}
    current_filename = None
    current_content = []
    lines = text.split('\n')
    
    for line in lines:
        if line.startswith('# FILENAME:'):
            if current_filename:
                files[current_filename] = '\n'.join(current_content).strip()
            current_filename = line.replace('# FILENAME:', '').strip()
            current_content = []
        elif current_filename:
            current_content.append(line)
    
    if current_filename:
        files[current_filename] = '\n'.join(current_content).strip()

    if not files:
        print("⚠️ مدل فرمت درخواستی را رعایت نکرد. کل پاسخ در فایل output.md ذخیره می‌شود.")
        clean_text = text.replace('```', '')
        files = {"output.md": f"# Raw AI Output\n\n{clean_text}"}
    
    return files


def create_github_repo(repo_name):
    try:
        g = Github(os.environ['GH_PAT'])
        user = g.get_user()
        repo = user.create_repo(
            name=repo_name,
            description="🤖 Generated by AI Code Generator",
            auto_init=True
        )
        print(f"✅ مخزن جدید ساخته شد: {repo.html_url}")
        return repo
    except Exception as e:
        print(f"❌ خطای مهلک در ساخت مخزن: {e}")
        sys.exit(1)


def push_files_to_repo(repo, files):
    for filename, content in files.items():
        try:
            try:
                existing = repo.get_contents(filename)
                repo.update_file(path=filename, message=f"AI Update: {filename}", content=content, sha=existing.sha)
                print(f"🔄 بروزرسانی: {filename}")
            except:
                repo.create_file(path=filename, message=f"AI Commit: {filename}", content=content)
                print(f"➕ ایجاد: {filename}")
        except Exception as e:
            print(f"❌ خطا در آپلود {filename}: {e}")


def comment_on_issue(repo_name, issue_number, new_repo_url):
    try:
        g = Github(os.environ['GH_PAT'])
        repo = g.get_repo(f"{os.environ['REPO_OWNER']}/{repo_name}")
        issue = repo.get_issue(number=issue_number)
        comment = (
            "🎉 **پروژه شما آماده است!**\n\n"
            "کدهای خواسته‌شده در یک مخزن جدید قرار گرفتند:\n\n"
            f"👉 **{new_repo_url}**\n\n"
            "کافیه روی لینک بالا کلیک کنی و پروژه‌ات رو ببینی.\n\n"
            "---\n"
            f"🤖 *این پروژه توسط [AI Code Generator](https://github.com/{os.environ['REPO_OWNER']}/{repo_name}) ساخته شده است.*"
        )
        issue.create_comment(comment)
        print(f"💬 کامنت روی Issue #{issue_number} ثبت شد.")
    except Exception as e:
        print(f"⚠️ خطا در ثبت کامنت (اما مخزن ساخته شده): {e}")


def main():
    print("🔄 دریافت درخواست کاربر...")
    prompt, issue_number = extract_prompt()
    if not prompt:
        print("❌ هیچ درخواستی یافت نشد.")
        sys.exit(1)
    
    print(f"📝 درخواست: {prompt[:200]}...")
    
    print("\n🤖 تلاش برای اتصال به مدل‌های مختلف Google AI...")
    try:
        generated = generate_code(prompt)
    except Exception as e:
        print(f"❌ خطای نهایی هوش مصنوعی: {e}")
        sys.exit(1)
    
    print("📦 تجزیه پاسخ...")
    files = parse_response_to_files(generated)
    print(f"📂 {len(files)} فایل آماده شد:")
    for f in files:
        print(f"   - {f}")
    
    repo_name = f"ai-project-{os.environ.get('GITHUB_RUN_ID', 'unknown')}"
    print(f"\n🏗️ ساخت مخزن: {repo_name}")
    new_repo = create_github_repo(repo_name)
    
    print("🚀 آپلود فایل‌ها...")
    push_files_to_repo(new_repo, files)
    
    if issue_number:
        current_repo = os.environ.get('GITHUB_REPOSITORY', '').split('/')[-1]
        comment_on_issue(current_repo, issue_number, new_repo.html_url)
    
    print("\n✅ عملیات با موفقیت پایان یافت.")


if __name__ == "__main__":
    main()
